### ISSUE TITLE
About the number of images in the validation set

### ISSUE THREAD

**Issue by Lwzzzzzz** [henghuiding/ReLA#18]
Hi, I noticed that you updated the dataset on August 29th, but why are there more samples in the validation set in the new dataset?

And Which version of the dataset was used to achieve the results in your paper?

**Comment by henghuiding** [comment]
Hi,

Thank you for your keen observation and raising this issue! 

The increase in the validation set is due to the addition of single-target expressions that were previously missing. We proofread and updated the dataset accordingly on Aug 29th. The results presented in our paper are derived from current release version. Please kindly update your local version to the current release. Thank you:)

**Comment by Lwzzzzzz** [comment]
Thanks！However, after evaluating using the checkpoint provided by you, the results I obtained for Pr@0.7 and Pr@0.8 are much lower than those given in the paper.

"Pr@0.7": 69.15387722132472,
"Pr@0.8": 57.01736672051696,
"Pr@0.9": 23.556138933764135

But in the paper, they are 74.20, 68.33, and 24.68 respectively.Have I made a mistake somewhere?

**Comment by ntuLC** [comment]
Feel free to utilize the results as a reference when making comparisons with ReLA in your paper, and it would be better to mark them as "reproduced". We will check the Pr@x and checkpoints. Thank you!

**Comment by Lwzzzzzz** [comment]
Thanks! I will also check the code I used for evaluate, perhaps the metrics are calculated incorrectly.

**Comment by RobertLuo1** [comment]
Sorry for bothering, I evaluate the R50 checkpoints provided in the github and I found that it is not matched with the results proposed in the readme. I am wondering if any problem?
